Task-2 - components
kornienko199004/junior-course-boilerplate pull request #3
Opened 2020-10-18 15:52 UTC by kornienko199004

2020-10-21 15:57 UTC, vislogurov requested changes

2020-10-21 15:57 UTC, vislogurov commented on src/index.js
> +import mock from './mock.js';
А какая разница между data и mock? Зачем дополнительную абстракцию вводить, если можно итерироваться сразу по data.json?

2020-10-21 15:57 UTC, vislogurov commented on src/components/List/List.js
> +  return <div className={s['goods-list']}>{props.children}</div>;
Если это "List" и он принимает `li`, то почему это `div`, а не `li`?

2020-10-21 15:57 UTC, vislogurov commented on src/components/ProductItem/ProductItem.js
> +function ProductItem({ isInStock, img, title, price, subPriceContent, maxRating, rating, ratingComponent }) {
`import ProductItem from 'csssr-school-product-card';`

В задании: Замени li на специально заготовленный сторонний компонент. Изучи его API и пробрось туда необходимые props.

Получается теряется часть, где тебе нужно API стороннего пакета изучить, а это полезный навык.

2020-10-21 15:57 UTC, vislogurov commented on src/components/Title/Title.js
> +  return <h1 className={s.title}>{props.content}</h1>;
Что, если тебе понадобится несколько заголовков разного уровня? Сейчас жёстко прописан `h1`, сеошники и поисковые краулеры сойдут с ума, если обнаружат несколько h1 на одной странице. 

Нужно предусмотреть возможность выбора тэга для Title

2020-10-21 17:05 UTC, kornienko199004 commented on src/index.js
> +import mock from './mock.js';
Разницы никакой. Такая реализация связана с идеей не вносить изменения в data.json, якобы они приходят с сервера в таком виде. 
Соединю два файла в один.

2020-10-21 17:05 UTC, kornienko199004 commented on src/components/ProductItem/ProductItem.js
> +function ProductItem({ isInStock, img, title, price, subPriceContent, maxRating, rating, ratingComponent }) {
Не совсем ясно, как устанавливать ```'csssr-school-product-card'``` . Пробовал установить с помощью npm, пакет не находится.
Как лучше установить эту зависимость?

2020-10-21 19:41 UTC, kornienko199004 commented
Исправил все замечания

2020-10-22 06:34 UTC, vislogurov approved these changes

2020-10-22 07:06 UTC, merged